[project]
name = "arcadia-impact-work-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
	"accelerate",
	"gym-sokoban",
	"matplotlib",
	"numpy",
	"setuptools",
	"torch",
	"transformer-lens",
	"transformers",
]
